language: node_js
node_js:
- '0.10'
install:
- npm install
- bower install
cache:
  bundler: true
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_30ab255abf6a_key -iv $encrypted_30ab255abf6a_iv
  -in secret.txt.enc -out secret.txt -d
