language: node_js
node_js:
  - '0.10'
before_install:
  - openssl aes-256-cbc -K $encrypted_30ab255abf6a_key -iv $encrypted_30ab255abf6a_iv -in secret.txt.enc -out secret.txt -d
  - gem install compass
  - npm install -g grunt-cli
install:
  - npm install
  - bower install
before_script:
  - grunt build:dist
cache:
  bundler: true
  directories:
    - node_modules
after_success:
  - git config --global user.name "Lucas Paulger"
  - git config --global user.email "lucas.paulger@gmail.com"
  - grunt buildcontrol:pages