language: node_js
node_js:
  - '0.10'
install:
  - npm install
  - bower install
cache:
  bundler: true
  directories:
    - node_modules
after_success:
  - grunt build:dist
  - grunt buildcontrol:pages
