language: node_js
node_js:
- '0.10'
before_install:
- gem install compass
- npm install -g grunt-cli
- npm install -g bower
install:
- npm install
- bower install
script:
- grunt test:dist
- grunt build:dist
cache:
  bundler: true
  directories:
  - node_modules
after_success:
- git config --global user.name "Lucas Paulger"
- git config --global user.email "lucas.paulger@gmail.com"
- grunt buildcontrol:pages

env:
  global:
    secure: ZOUtcOqHNinpRmZ2/SpYWk787Kg6RN8TlvgalGRaB24JkXh++0i8VV45Jid+CEPxVrs//S6UGd0R5Xxtop9lSLwVVs60NOXKWATt719UdVqlJv9i/7QQ/vmZXZqnX8OaBOU91J8PvfkRpjp9Dd1ECG/Iu1BBDwb2TaEjXVUuwxw=
