language: node_js
node_js:
  - '0.10'
before_install:
  - gem install compass
  - npm install -g grunt-cli
install:
  - npm install
  - bower install
before_script:
  - grunt build:dist
cache:
  bundler: true
  directories:
    - node_modules
after_success:
  - grunt buildcontrol:pages
